<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mail</title>
</head>
<body>
    <p>Dear %studfname% %studlname% ,<br><br>You have Applied for %courseid % %classid% <br><br> Portal Login details :<br><br>Email :%email% <br>Password : %password% <br><br>Regards,<br>SMILE 4 Kids Indian Language School.<br><a href="https://smile4kids.co.uk" target="_blank">smile4kids.co.uk</a></p>
</body>
</html>
